/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "index": {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    meta: undefined,
  },
  "number-ticker": {
    name: "number-ticker",
    description: "Animate numbers to count up or down to a target number",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/magicui/number-ticker.tsx",
      type: "registry:ui",
      target: "components/magicui/number-ticker.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/magicui/number-ticker.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "animated-shiny-text": {
    name: "animated-shiny-text",
    description: "A light glare effect which pans across text making it appear as if it is shimmering.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/magicui/animated-shiny-text.tsx",
      type: "registry:ui",
      target: "components/magicui/animated-shiny-text.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/magicui/animated-shiny-text.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "text-animate": {
    name: "text-animate",
    description: "A text animation component that animates text using a variety of different animations.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/magicui/text-animate.tsx",
      type: "registry:ui",
      target: "components/magicui/text-animate.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/magicui/text-animate.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "floating-phone": {
    name: "floating-phone",
    description: "A floating phone component",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/pioneerui/floating-phone.tsx",
      type: "registry:ui",
      target: "components/pioneerui/floating-phone.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pioneerui/floating-phone.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "link-reveal": {
    name: "link-reveal",
    description: "Link reveal effect",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/pioneerui/link-reveal.tsx",
      type: "registry:ui",
      target: "components/pioneerui/link-reveal.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pioneerui/link-reveal.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "shimmer-button": {
    name: "shimmer-button",
    description: "A shimmering button component",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/pioneerui/shimmer-button.tsx",
      type: "registry:ui",
      target: "components/pioneerui/shimmer-button.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pioneerui/shimmer-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "hover-links": {
    name: "hover-links",
    description: "A collection of links with hover effects",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/pioneerui/hover-links.tsx",
      type: "registry:ui",
      target: "components/pioneerui/hover-links.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pioneerui/hover-links.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "spinning-text": {
    name: "spinning-text",
    description: "A spinning text component",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/pioneerui/spinning-text.tsx",
      type: "registry:ui",
      target: "components/pioneerui/spinning-text.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pioneerui/spinning-text.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "simple-date-selector": {
    name: "simple-date-selector",
    description: "A simple date selector component",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/pioneerui/simple-date-selector.tsx",
      type: "registry:ui",
      target: "components/pioneerui/simple-date-selector.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pioneerui/simple-date-selector.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "shiny-button": {
    name: "shiny-button",
    description: "A shiny button component",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/pioneerui/shiny-button.tsx",
      type: "registry:ui",
      target: "components/pioneerui/shiny-button.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pioneerui/shiny-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "neu-button": {
    name: "neu-button",
    description: "A neu button component",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/pioneerui/neu-button.tsx",
      type: "registry:ui",
      target: "components/pioneerui/neu-button.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pioneerui/neu-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "countup-stats": {
    name: "countup-stats",
    description: "A count up stats component",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/pioneerui/countup-stats.tsx",
      type: "registry:ui",
      target: "components/pioneerui/countup-stats.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pioneerui/countup-stats.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "hover-button": {
    name: "hover-button",
    description: "A hover button component",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/pioneerui/hover-button.tsx",
      type: "registry:ui",
      target: "components/pioneerui/hover-button.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pioneerui/hover-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "typewriter": {
    name: "typewriter",
    description: "A typewriter effect component",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/pioneerui/typewriter.tsx",
      type: "registry:ui",
      target: "components/pioneerui/typewriter.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pioneerui/typewriter.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "particle-background": {
    name: "particle-background",
    description: "A particle background component",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/pioneerui/particle-background.tsx",
      type: "registry:ui",
      target: "components/pioneerui/particle-background.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pioneerui/particle-background.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "text-scramble": {
    name: "text-scramble",
    description: "A text scramble effect component",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/pioneerui/text-scramble.tsx",
      type: "registry:ui",
      target: "components/pioneerui/text-scramble.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pioneerui/text-scramble.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "dock": {
    name: "dock",
    description: "A dock component",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/pioneerui/dock.tsx",
      type: "registry:ui",
      target: "components/pioneerui/dock.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pioneerui/dock.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "shimmer-button-demo": {
    name: "shimmer-button-demo",
    description: "Example showing a button with a shimmering light effect.",
    type: "registry:example",
    registryDependencies: ["https://pioneerui.com/r/shimmer-button"],
    files: [{
      path: "registry/example/shimmer-button-demo.tsx",
      type: "registry:example",
      target: "components/shimmer-button-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/shimmer-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "number-ticker-demo": {
    name: "number-ticker-demo",
    description: "Example showing animated counting numbers.",
    type: "registry:example",
    registryDependencies: ["https://magicui.design/r/number-ticker"],
    files: [{
      path: "registry/example/number-ticker-demo.tsx",
      type: "registry:example",
      target: "components/number-ticker-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/number-ticker-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "number-ticker-decimal-demo": {
    name: "number-ticker-decimal-demo",
    description: "Example showing animated counting decimal numbers.",
    type: "registry:example",
    registryDependencies: ["https://magicui.design/r/number-ticker"],
    files: [{
      path: "registry/example/number-ticker-decimal-demo.tsx",
      type: "registry:example",
      target: "components/number-ticker-decimal-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/number-ticker-decimal-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "text-animate-demo-2": {
    name: "text-animate-demo-2",
    description: "Second example showing various text animations.",
    type: "registry:example",
    registryDependencies: ["https://magicui.design/r/text-animate"],
    files: [{
      path: "registry/example/text-animate-demo-2.tsx",
      type: "registry:example",
      target: "components/text-animate-demo-2.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/text-animate-demo-2.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "text-animate-demo-3": {
    name: "text-animate-demo-3",
    description: "Third example showing various text animations.",
    type: "registry:example",
    registryDependencies: ["https://magicui.design/r/text-animate"],
    files: [{
      path: "registry/example/text-animate-demo-3.tsx",
      type: "registry:example",
      target: "components/text-animate-demo-3.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/text-animate-demo-3.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "floating-phone-demo": {
    name: "floating-phone-demo",
    description: "Example showing a floating phone mockup.",
    type: "registry:example",
    registryDependencies: ["https://pioneerui.com/r/floating-phone"],
    files: [{
      path: "registry/example/floating-phone-demo.tsx",
      type: "registry:example",
      target: "components/floating-phone-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/floating-phone-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "floating-phone-demo-2": {
    name: "floating-phone-demo-2",
    description: "Second example showing a floating phone mockup.",
    type: "registry:example",
    registryDependencies: ["https://pioneerui.com/r/floating-phone"],
    files: [{
      path: "registry/example/floating-phone-demo-2.tsx",
      type: "registry:example",
      target: "components/floating-phone-demo-2.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/floating-phone-demo-2.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "floating-phone-demo-3": {
    name: "floating-phone-demo-3",
    description: "Third example showing a floating phone mockup.",
    type: "registry:example",
    registryDependencies: ["https://pioneerui.com/r/floating-phone"],
    files: [{
      path: "registry/example/floating-phone-demo-3.tsx",
      type: "registry:example",
      target: "components/floating-phone-demo-3.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/floating-phone-demo-3.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "link-demo": {
    name: "link-demo",
    description: "Example showing animated link hover effects.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/example/link-demo.tsx",
      type: "registry:example",
      target: "components/link-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/link-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "hover-link-demo": {
    name: "hover-link-demo",
    description: "Example showing a collection of links with hover effects.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/example/hover-link-demo.tsx",
      type: "registry:example",
      target: "components/hover-link-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/hover-link-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "spinning-text-demo": {
    name: "spinning-text-demo",
    description: "Example showing spinning text effect.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/example/spinning-text-demo.tsx",
      type: "registry:example",
      target: "components/spinning-text-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/spinning-text-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "date-selector-demo": {
    name: "date-selector-demo",
    description: "Example showing a simple date selector component.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/example/date-selector-demo.tsx",
      type: "registry:example",
      target: "components/date-selector-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/date-selector-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "shiny-button-demo": {
    name: "shiny-button-demo",
    description: "Example showing a button with a shine effect.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/example/shiny-button-demo.tsx",
      type: "registry:example",
      target: "components/shiny-button-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/shiny-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "neu-button-demo": {
    name: "neu-button-demo",
    description: "Example showing a button with a neumorphic effect.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/example/neu-button-demo.tsx",
      type: "registry:example",
      target: "components/neu-button-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/neu-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "countup-stats-demo": {
    name: "countup-stats-demo",
    description: "Example showing animated counting numbers.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/example/countup-stats-demo.tsx",
      type: "registry:example",
      target: "components/countup-stats-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/countup-stats-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "hover-button-demo": {
    name: "hover-button-demo",
    description: "Example showing a button with hover effects.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/example/hover-button-demo.tsx",
      type: "registry:example",
      target: "components/hover-button-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/hover-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "typewriter-demo": {
    name: "typewriter-demo",
    description: "Example showing a typewriter effect.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/example/typewriter-demo.tsx",
      type: "registry:example",
      target: "components/typewriter-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/typewriter-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "particle-background-demo": {
    name: "particle-background-demo",
    description: "Example showing a particle background effect.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/example/particle-background-demo.tsx",
      type: "registry:example",
      target: "components/particle-background-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/particle-background-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "text-scramble-demo": {
    name: "text-scramble-demo",
    description: "Example showing a text scramble effect.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/example/text-scramble-demo.tsx",
      type: "registry:example",
      target: "components/text-scramble-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/text-scramble-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "dock-demo": {
    name: "dock-demo",
    description: "Example showing a dock component.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/example/dock-demo.tsx",
      type: "registry:example",
      target: "components/dock-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/dock-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "countup-stats-demo-2": {
    name: "countup-stats-demo-2",
    description: "Example showing animated counting numbers.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/example/countup-stats-demo-2.tsx",
      type: "registry:example",
      target: "components/countup-stats-demo-2.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/countup-stats-demo-2.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "countup-stats-demo-3": {
    name: "countup-stats-demo-3",
    description: "Example showing animated counting numbers.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/example/countup-stats-demo-3.tsx",
      type: "registry:example",
      target: "components/countup-stats-demo-3.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/countup-stats-demo-3.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "registry/lib/utils.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/utils.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  }